import puppeteer from "puppeteer";
const APP="http://localhost:3650"; const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const DIR="public/shots";
const b=await puppeteer.launch({headless:true,args:["--no-sandbox"],protocolTimeout:90000});
const wait=async(p,fn,ms=12000,...a)=>{const t=Date.now();while(Date.now()-t<ms){if(await p.evaluate(fn,...a))return true;await sleep(200);}return false;};
const clickText=(p,t)=>p.evaluate(t=>[...document.querySelectorAll("button,a")].find(x=>x.textContent.trim()===t)?.click(),t);
const clickAria=(p,l)=>p.evaluate(l=>document.querySelector(`[aria-label="${l}"]`)?.click(),l);
async function mobile(name){
  const ctx=await b.createBrowserContext();
  const p=await ctx.newPage();
  await p.setViewport({width:390,height:844,deviceScaleFactor:2,isMobile:true,hasTouch:true});
  await p.goto(APP,{waitUntil:"load"}); await sleep(700);
  await p.evaluate(async n=>{await fetch("/api/auth/sign-up/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:`${n.replace(/\s/g,'')}_${Date.now()}@e2e.dev`,password:"hunter2pw",name:n}),credentials:"include"});},name);
  await p.reload({waitUntil:"load"});
  return p;
}
const p=await mobile("Phone User");
await wait(p,()=>/Create your first orbit/.test(document.body.innerText));
await clickText(p,"Join"); await sleep(300);
await p.type('input[placeholder="e.g. 7QK2ZP"]',"WELCOME"); await clickText(p,"Join orbit");
await wait(p,()=>[...document.querySelectorAll("nav a")].some(a=>/engineering/.test(a.textContent))); await sleep(1500);
await p.screenshot({path:`${DIR}/1-chat.png`});
await clickAria(p,"Open channels"); await sleep(500);
await p.screenshot({path:`${DIR}/2-channels-drawer.png`});
await p.evaluate(()=>document.querySelector('.bg-black\\/50')?.click()); await sleep(400);
await clickAria(p,"Toggle members"); await sleep(500);
await p.screenshot({path:`${DIR}/3-members-drawer.png`});
await clickAria(p,"Toggle members"); await sleep(300);
await clickAria(p,"Settings"); await sleep(600);
await p.screenshot({path:`${DIR}/4-profile.png`});
const o=await mobile("Phone Owner");
await wait(o,()=>/Create your first orbit/.test(document.body.innerText));
await o.type('input[placeholder="Acme HQ"]',"My Orbit"); await clickText(o,"Create orbit");
await wait(o,()=>/general/.test(document.body.innerText)); await sleep(600);
await clickAria(o,"Open channels"); await sleep(400);
await o.evaluate(()=>[...document.querySelectorAll('aside [role="button"], aside button')].find(x=>/My Orbit/.test(x.textContent))?.click());
await wait(o,()=>/Orbit settings/.test(document.body.innerText),4000); await clickText(o,"Orbit settings");
await wait(o,()=>/Invites/.test(document.body.innerText),4000); await clickText(o,"Invites"); await sleep(500);
await o.screenshot({path:`${DIR}/5-settings.png`});
await b.close();
console.log("OK screenshots written");
