// A curated, dependency-free unicode emoji set for the picker. Each entry is
// [emoji, "search keywords"]; categories drive the tab strip. Not exhaustive —
// a few hundred of the most-used emoji across categories, which keeps the bundle
// small while still feeling complete for a chat app.

export interface EmojiCategory {
  key: string;
  label: string;
  icon: string; // a representative emoji used as the tab glyph
  emojis: ReadonlyArray<readonly [string, string]>;
}

export const EMOJI_CATEGORIES: ReadonlyArray<EmojiCategory> = [
  {
    key: "smileys",
    label: "Smileys & Emotion",
    icon: "😀",
    emojis: [
      ["😀", "grinning smile happy"],
      ["😃", "smile happy joy"],
      ["😄", "smile happy laugh"],
      ["😁", "grin beaming"],
      ["😆", "laughing satisfied"],
      ["😅", "sweat smile relief nervous"],
      ["🤣", "rofl rolling laughing"],
      ["😂", "joy tears laughing crying"],
      ["🙂", "slight smile"],
      ["🙃", "upside down silly"],
      ["😉", "wink flirt"],
      ["😊", "blush happy smile"],
      ["😇", "innocent angel halo"],
      ["🥰", "loving hearts adore"],
      ["😍", "heart eyes love"],
      ["🤩", "star struck excited"],
      ["😘", "kiss blow love"],
      ["😗", "kissing"],
      ["😋", "yum tasty tongue"],
      ["😛", "tongue playful"],
      ["😜", "wink tongue silly"],
      ["🤪", "zany goofy crazy"],
      ["🤨", "raised eyebrow skeptical"],
      ["🧐", "monocle inspect"],
      ["🤓", "nerd glasses"],
      ["😎", "cool sunglasses"],
      ["🥳", "party celebrate"],
      ["😏", "smirk"],
      ["😒", "unamused meh"],
      ["😞", "disappointed sad"],
      ["😔", "pensive sad"],
      ["😟", "worried"],
      ["😕", "confused"],
      ["🙁", "frown slight sad"],
      ["😣", "persevere"],
      ["😫", "tired"],
      ["😩", "weary"],
      ["🥺", "pleading puppy eyes"],
      ["😢", "cry sad tear"],
      ["😭", "sob crying loud"],
      ["😤", "triumph steam huff"],
      ["😠", "angry mad"],
      ["😡", "rage furious"],
      ["🤬", "swearing cursing"],
      ["🤯", "mind blown shocked"],
      ["😳", "flushed embarrassed"],
      ["🥵", "hot heat sweat"],
      ["🥶", "cold freezing"],
      ["😱", "scream fear shock"],
      ["😨", "fearful scared"],
      ["😰", "anxious sweat"],
      ["😥", "sad relieved"],
      ["🤗", "hug hugging"],
      ["🤔", "thinking hmm"],
      ["🤭", "giggle oops hand"],
      ["🤫", "shush quiet"],
      ["🤥", "lying liar"],
      ["😶", "no mouth speechless"],
      ["😐", "neutral meh"],
      ["😑", "expressionless"],
      ["😬", "grimace awkward"],
      ["🙄", "eye roll"],
      ["😯", "hushed surprised"],
      ["😴", "sleeping zzz tired"],
      ["🤤", "drool"],
      ["😪", "sleepy"],
      ["😵", "dizzy knocked out"],
      ["🤐", "zipper mouth quiet"],
      ["🥴", "woozy drunk"],
      ["🤢", "nauseated sick"],
      ["🤮", "vomit sick"],
      ["🤧", "sneeze sick"],
      ["😷", "mask sick"],
      ["🤒", "thermometer sick ill"],
      ["🤕", "bandage hurt injured"],
      ["😈", "devil smiling horns"],
      ["👿", "imp angry devil"],
      ["💀", "skull dead"],
      ["💩", "poop"],
      ["🤡", "clown"],
      ["👻", "ghost boo"],
      ["👽", "alien"],
      ["🤖", "robot bot"],
    ],
  },
  {
    key: "people",
    label: "People & Gestures",
    icon: "👋",
    emojis: [
      ["👋", "wave hello hi bye"],
      ["🤚", "raised back hand"],
      ["✋", "raised hand stop high five"],
      ["🖐️", "hand fingers splayed"],
      ["🖖", "vulcan spock"],
      ["👌", "ok perfect"],
      ["🤌", "pinched fingers italian"],
      ["🤏", "pinch small"],
      ["✌️", "victory peace"],
      ["🤞", "fingers crossed luck"],
      ["🤟", "love you gesture"],
      ["🤘", "rock horns"],
      ["🤙", "call me shaka"],
      ["👈", "point left"],
      ["👉", "point right"],
      ["👆", "point up"],
      ["👇", "point down"],
      ["☝️", "index point up"],
      ["👍", "thumbs up like yes approve"],
      ["👎", "thumbs down dislike no"],
      ["✊", "fist raised"],
      ["👊", "fist bump punch"],
      ["🤛", "fist left"],
      ["🤜", "fist right"],
      ["👏", "clap applause"],
      ["🙌", "raised hands celebrate praise"],
      ["👐", "open hands"],
      ["🤲", "palms together"],
      ["🙏", "pray thanks please"],
      ["🤝", "handshake deal"],
      ["💪", "muscle strong flex"],
      ["✍️", "writing hand"],
      ["💅", "nails sassy"],
      ["👀", "eyes looking"],
      ["👁️", "eye"],
      ["🧠", "brain smart"],
      ["👶", "baby"],
      ["🧒", "child"],
      ["👦", "boy"],
      ["👧", "girl"],
      ["🧑", "person adult"],
      ["👨", "man"],
      ["👩", "woman"],
      ["🧔", "beard"],
      ["👮", "police cop"],
      ["🕵️", "detective spy"],
      ["💂", "guard"],
      ["👷", "construction worker"],
      ["🤴", "prince"],
      ["👸", "princess"],
      ["🦸", "superhero"],
      ["🦹", "supervillain"],
      ["🎅", "santa christmas"],
      ["🧙", "wizard mage"],
      ["🧛", "vampire"],
      ["🧟", "zombie"],
      ["💃", "dancer dancing"],
      ["🕺", "man dancing"],
      ["👯", "dancers party"],
      ["🚶", "walking"],
      ["🏃", "running run"],
    ],
  },
  {
    key: "nature",
    label: "Animals & Nature",
    icon: "🐶",
    emojis: [
      ["🐶", "dog puppy"],
      ["🐱", "cat kitten"],
      ["🐭", "mouse"],
      ["🐹", "hamster"],
      ["🐰", "rabbit bunny"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🐨", "koala"],
      ["🐯", "tiger"],
      ["🦁", "lion"],
      ["🐮", "cow"],
      ["🐷", "pig"],
      ["🐸", "frog"],
      ["🐵", "monkey"],
      ["🐔", "chicken"],
      ["🐧", "penguin"],
      ["🐦", "bird"],
      ["🦅", "eagle"],
      ["🦉", "owl"],
      ["🦄", "unicorn"],
      ["🐝", "bee"],
      ["🦋", "butterfly"],
      ["🐌", "snail"],
      ["🐞", "ladybug"],
      ["🐢", "turtle"],
      ["🐍", "snake"],
      ["🐙", "octopus"],
      ["🦑", "squid"],
      ["🦀", "crab"],
      ["🐠", "fish tropical"],
      ["🐬", "dolphin"],
      ["🐳", "whale"],
      ["🦈", "shark"],
      ["🐊", "crocodile"],
      ["🐘", "elephant"],
      ["🦒", "giraffe"],
      ["🦓", "zebra"],
      ["🐴", "horse"],
      ["🐑", "sheep"],
      ["🐺", "wolf"],
      ["🦎", "lizard"],
      ["🌵", "cactus"],
      ["🌲", "evergreen tree"],
      ["🌳", "tree"],
      ["🌴", "palm tree"],
      ["🌱", "seedling sprout"],
      ["🍀", "clover luck"],
      ["🍁", "maple leaf autumn"],
      ["🍂", "fallen leaves autumn"],
      ["🌸", "blossom cherry flower"],
      ["🌺", "hibiscus flower"],
      ["🌻", "sunflower"],
      ["🌹", "rose flower"],
      ["🌷", "tulip flower"],
      ["🌼", "daisy flower"],
      ["⭐", "star"],
      ["🌟", "glowing star sparkle"],
      ["✨", "sparkles shine"],
      ["⚡", "lightning bolt zap"],
      ["🔥", "fire lit hot flame"],
      ["💥", "boom explosion collision"],
      ["🌈", "rainbow"],
      ["☀️", "sun sunny"],
      ["🌙", "moon crescent night"],
      ["☁️", "cloud"],
      ["🌧️", "rain"],
      ["❄️", "snowflake cold"],
      ["💧", "droplet water"],
      ["🌊", "wave ocean water"],
    ],
  },
  {
    key: "food",
    label: "Food & Drink",
    icon: "🍔",
    emojis: [
      ["🍏", "green apple"],
      ["🍎", "apple"],
      ["🍐", "pear"],
      ["🍊", "orange tangerine"],
      ["🍋", "lemon"],
      ["🍌", "banana"],
      ["🍉", "watermelon"],
      ["🍇", "grapes"],
      ["🍓", "strawberry"],
      ["🫐", "blueberries"],
      ["🍒", "cherries"],
      ["🍑", "peach"],
      ["🥭", "mango"],
      ["🍍", "pineapple"],
      ["🥥", "coconut"],
      ["🥝", "kiwi"],
      ["🍅", "tomato"],
      ["🥑", "avocado"],
      ["🍆", "eggplant"],
      ["🥦", "broccoli"],
      ["🌽", "corn"],
      ["🥕", "carrot"],
      ["🥔", "potato"],
      ["🍞", "bread"],
      ["🥐", "croissant"],
      ["🥯", "bagel"],
      ["🧀", "cheese"],
      ["🥚", "egg"],
      ["🍳", "fried egg cooking"],
      ["🥞", "pancakes"],
      ["🧇", "waffle"],
      ["🥓", "bacon"],
      ["🍔", "burger hamburger"],
      ["🍟", "fries"],
      ["🍕", "pizza"],
      ["🌭", "hot dog"],
      ["🥪", "sandwich"],
      ["🌮", "taco"],
      ["🌯", "burrito"],
      ["🥗", "salad"],
      ["🍝", "pasta spaghetti"],
      ["🍜", "ramen noodles"],
      ["🍲", "stew pot"],
      ["🍣", "sushi"],
      ["🍱", "bento"],
      ["🍙", "rice ball"],
      ["🍚", "rice"],
      ["🍛", "curry"],
      ["🍤", "shrimp tempura fried"],
      ["🍦", "ice cream soft serve"],
      ["🍰", "cake slice"],
      ["🎂", "birthday cake"],
      ["🧁", "cupcake"],
      ["🍪", "cookie"],
      ["🍩", "donut"],
      ["🍫", "chocolate"],
      ["🍬", "candy"],
      ["🍭", "lollipop"],
      ["🍿", "popcorn"],
      ["☕", "coffee hot drink"],
      ["🍵", "tea"],
      ["🧃", "juice box"],
      ["🥤", "soda cup drink"],
      ["🍺", "beer"],
      ["🍻", "beers cheers"],
      ["🥂", "champagne cheers toast"],
      ["🍷", "wine"],
      ["🍸", "cocktail martini"],
      ["🍹", "tropical drink"],
      ["🍾", "champagne bottle"],
    ],
  },
  {
    key: "activities",
    label: "Activities",
    icon: "🎉",
    emojis: [
      ["⚽", "soccer football"],
      ["🏀", "basketball"],
      ["🏈", "american football"],
      ["⚾", "baseball"],
      ["🥎", "softball"],
      ["🎾", "tennis"],
      ["🏐", "volleyball"],
      ["🏉", "rugby"],
      ["🎱", "8 ball pool billiards"],
      ["🏓", "ping pong table tennis"],
      ["🏸", "badminton"],
      ["🥅", "goal net"],
      ["🏒", "hockey"],
      ["🏑", "field hockey"],
      ["🥍", "lacrosse"],
      ["🏏", "cricket"],
      ["⛳", "golf flag"],
      ["🏹", "bow arrow archery"],
      ["🎣", "fishing"],
      ["🥊", "boxing glove"],
      ["🥋", "martial arts karate"],
      ["⛸️", "ice skate"],
      ["🛹", "skateboard"],
      ["🛷", "sled"],
      ["🎿", "ski"],
      ["⛷️", "skier"],
      ["🏂", "snowboard"],
      ["🏋️", "weightlifting gym"],
      ["🤸", "cartwheel gymnastics"],
      ["🤼", "wrestling"],
      ["🤽", "water polo"],
      ["🚴", "cycling bike"],
      ["🏆", "trophy win champion"],
      ["🥇", "first place gold medal"],
      ["🥈", "second place silver medal"],
      ["🥉", "third place bronze medal"],
      ["🏅", "medal sports"],
      ["🎖️", "military medal"],
      ["🎯", "dart bullseye target"],
      ["🎮", "game controller gaming"],
      ["🕹️", "joystick arcade"],
      ["🎲", "dice"],
      ["🎰", "slot machine"],
      ["🎳", "bowling"],
      ["🎨", "art palette paint"],
      ["🎭", "theater drama masks"],
      ["🎤", "microphone sing karaoke"],
      ["🎧", "headphones music"],
      ["🎼", "musical score"],
      ["🎹", "piano keyboard"],
      ["🥁", "drum"],
      ["🎸", "guitar"],
      ["🎺", "trumpet"],
      ["🎻", "violin"],
      ["🎉", "party tada celebrate congrats"],
      ["🎊", "confetti party"],
      ["🎈", "balloon"],
      ["🎁", "gift present"],
      ["🎀", "ribbon bow"],
      ["🎇", "fireworks sparkler"],
      ["🎆", "fireworks"],
      ["🪅", "pinata party"],
      ["🎃", "pumpkin halloween"],
      ["🎄", "christmas tree"],
    ],
  },
  {
    key: "travel",
    label: "Travel & Places",
    icon: "✈️",
    emojis: [
      ["🚗", "car"],
      ["🚕", "taxi"],
      ["🚙", "suv car"],
      ["🚌", "bus"],
      ["🏎️", "race car fast"],
      ["🚓", "police car"],
      ["🚑", "ambulance"],
      ["🚒", "fire truck"],
      ["🚜", "tractor"],
      ["🛵", "scooter moped"],
      ["🏍️", "motorcycle"],
      ["🚲", "bicycle bike"],
      ["🛴", "kick scooter"],
      ["🚂", "train locomotive"],
      ["🚆", "train"],
      ["🚇", "metro subway"],
      ["🚀", "rocket launch ship"],
      ["🛸", "ufo flying saucer"],
      ["✈️", "airplane flight travel"],
      ["🛩️", "small plane"],
      ["🚁", "helicopter"],
      ["⛵", "sailboat"],
      ["🚤", "speedboat"],
      ["🛥️", "motor boat"],
      ["🚢", "ship cruise"],
      ["⚓", "anchor"],
      ["🚧", "construction barrier"],
      ["⛽", "fuel gas"],
      ["🚦", "traffic light"],
      ["🗺️", "map world"],
      ["🗿", "moai statue"],
      ["🗽", "statue liberty"],
      ["🗼", "tower tokyo"],
      ["🏰", "castle"],
      ["🏯", "japanese castle"],
      ["🏟️", "stadium"],
      ["🎡", "ferris wheel"],
      ["🎢", "roller coaster"],
      ["🎠", "carousel"],
      ["⛲", "fountain"],
      ["⛺", "tent camping"],
      ["🏕️", "camping"],
      ["🏖️", "beach umbrella"],
      ["🏝️", "desert island"],
      ["⛰️", "mountain"],
      ["🏔️", "snow mountain"],
      ["🌋", "volcano"],
      ["🏠", "house home"],
      ["🏡", "house garden home"],
      ["🏢", "office building"],
      ["🏬", "department store"],
      ["🏨", "hotel"],
      ["🏫", "school"],
      ["🏥", "hospital"],
      ["⛪", "church"],
      ["🕌", "mosque"],
      ["🌆", "city dusk skyline"],
      ["🌃", "night city stars"],
      ["🌉", "bridge night"],
      ["🌁", "foggy"],
    ],
  },
  {
    key: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      ["⌚", "watch"],
      ["📱", "phone mobile"],
      ["💻", "laptop computer"],
      ["🖥️", "desktop computer"],
      ["⌨️", "keyboard"],
      ["🖱️", "mouse computer"],
      ["🖨️", "printer"],
      ["💾", "floppy save disk"],
      ["💿", "cd disc"],
      ["📷", "camera photo"],
      ["📸", "camera flash"],
      ["🎥", "movie camera film"],
      ["📹", "video camera"],
      ["📺", "tv television"],
      ["📻", "radio"],
      ["🔋", "battery"],
      ["🔌", "plug power"],
      ["💡", "idea lightbulb"],
      ["🔦", "flashlight"],
      ["🕯️", "candle"],
      ["📖", "book open read"],
      ["📚", "books stack"],
      ["📒", "ledger notebook"],
      ["📝", "memo note write"],
      ["✏️", "pencil"],
      ["🖊️", "pen"],
      ["🖌️", "paintbrush"],
      ["📌", "pin"],
      ["📍", "location pin"],
      ["📎", "paperclip"],
      ["✂️", "scissors cut"],
      ["📏", "ruler"],
      ["📐", "triangle ruler"],
      ["🔒", "lock locked"],
      ["🔓", "unlock open"],
      ["🔑", "key"],
      ["🔨", "hammer"],
      ["🪛", "screwdriver"],
      ["🔧", "wrench tool"],
      ["🪚", "saw"],
      ["⚙️", "gear settings"],
      ["🧰", "toolbox"],
      ["🧲", "magnet"],
      ["💊", "pill medicine"],
      ["💉", "syringe shot"],
      ["🩹", "bandage"],
      ["🌡️", "thermometer"],
      ["🧪", "test tube science"],
      ["🔬", "microscope"],
      ["🔭", "telescope"],
      ["📡", "satellite antenna"],
      ["💰", "money bag"],
      ["💵", "dollar cash money"],
      ["💳", "credit card"],
      ["💎", "gem diamond"],
      ["⚖️", "scales balance justice"],
      ["🛒", "shopping cart"],
      ["📦", "package box"],
      ["📬", "mailbox mail"],
      ["✉️", "envelope email"],
      ["📅", "calendar date"],
      ["📆", "calendar"],
      ["📈", "chart up growth"],
      ["📉", "chart down decline"],
      ["📊", "bar chart"],
      ["🔔", "bell notification"],
      ["🔕", "bell off mute"],
      ["🔍", "magnifying search"],
      ["🔑", "key"],
      ["🗑️", "trash bin delete"],
    ],
  },
  {
    key: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      ["❤️", "red heart love"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["🤍", "white heart"],
      ["🤎", "brown heart"],
      ["💔", "broken heart"],
      ["❤️‍🔥", "heart on fire"],
      ["💕", "two hearts"],
      ["💞", "revolving hearts"],
      ["💓", "beating heart"],
      ["💗", "growing heart"],
      ["💖", "sparkling heart"],
      ["💘", "heart arrow cupid"],
      ["💝", "heart gift"],
      ["💟", "heart decoration"],
      ["💯", "hundred 100 perfect"],
      ["💢", "anger symbol"],
      ["💬", "speech bubble"],
      ["💭", "thought bubble"],
      ["💤", "zzz sleep"],
      ["✅", "check mark green done yes"],
      ["☑️", "check box ticked"],
      ["✔️", "check mark"],
      ["❌", "cross x no wrong"],
      ["❎", "cross mark button"],
      ["➕", "plus add"],
      ["➖", "minus subtract"],
      ["➗", "divide"],
      ["❓", "question mark"],
      ["❗", "exclamation"],
      ["‼️", "double exclamation"],
      ["⁉️", "interrobang"],
      ["⚠️", "warning caution"],
      ["🚫", "no prohibited forbidden"],
      ["✳️", "eight spoked asterisk"],
      ["🔱", "trident"],
      ["⭕", "circle"],
      ["🆗", "ok button"],
      ["🆕", "new button"],
      ["🆒", "cool button"],
      ["🔝", "top arrow up"],
      ["🔙", "back arrow"],
      ["🎵", "music note"],
      ["🎶", "music notes"],
      ["♻️", "recycle"],
      ["⚜️", "fleur de lis"],
      ["🔰", "beginner"],
      ["✴️", "sparkle star"],
      ["💲", "dollar sign"],
      ["⚛️", "atom science"],
      ["☮️", "peace"],
      ["☯️", "yin yang"],
      ["✝️", "cross christian"],
      ["⭐", "star"],
      ["🌟", "glowing star"],
      ["🔥", "fire lit"],
      ["💀", "skull"],
      ["👍", "thumbs up like"],
      ["👀", "eyes"],
      ["🎉", "tada party"],
      ["🙏", "pray thanks"],
    ],
  },
] as const;

export interface FlatEmoji {
  char: string;
  keywords: string;
  category: string;
}

/** A de-duplicated flat list (some emoji appear in two categories) for search. */
export const ALL_EMOJI: ReadonlyArray<FlatEmoji> = (() => {
  const seen = new Set<string>();
  const out: FlatEmoji[] = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const [char, keywords] of cat.emojis) {
      if (seen.has(char)) continue;
      seen.add(char);
      out.push({ char, keywords, category: cat.key });
    }
  }
  return out;
})();

/** Substring search over names/keywords; empty query returns nothing. */
export function searchEmoji(query: string, limit = 60): FlatEmoji[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: FlatEmoji[] = [];
  for (const e of ALL_EMOJI) {
    if (e.keywords.includes(q)) {
      out.push(e);
      if (out.length >= limit) break;
    }
  }
  return out;
}
