import { relative } from "node:path"
import { type Discovery, scanExports } from "./discover.js"

/** A relative, POSIX, extensionless import specifier from `fromDir` to `target`. */
function importSpec(fromDir: string, target: string): string {
  let rel = relative(fromDir, target).replace(/\\/g, "/").replace(/\.ts$/, "")
  if (!rel.startsWith(".")) rel = "./" + rel
  return rel
}

function ident(name: string): string {
  return "_" + name.replace(/[^A-Za-z0-9_$]/g, "_")
}

/**
 * The generated Worker entry (emitted to `<backendRoot>/_generated/worker.ts`).
 * It imports the schema and every function module, assembles the `modules` map,
 * and exports the `RabbatPartition` Durable Object and the default Worker handler
 * — so the user never writes this wiring.
 */
export function generateWorkerEntry(disco: Discovery): string {
  const from = disco.generatedDir
  const lines: string[] = []
  lines.push("// Generated by @rabbat/vite. Do not edit.")
  lines.push(`import { compileSchema } from "@rabbat/schema"`)
  lines.push(`import { definePartition, defineWorker } from "@rabbat/server"`)
  lines.push(`import { schema } from ${JSON.stringify(importSpec(from, disco.schemaPath))}`)
  for (const m of disco.modules) {
    lines.push(`import * as ${ident(m.name)} from ${JSON.stringify(importSpec(from, m.path))}`)
  }
  if (disco.configPath) {
    lines.push(`import * as _config from ${JSON.stringify(importSpec(from, disco.configPath))}`)
  }
  lines.push("")
  lines.push(
    `const modules = {\n${disco.modules.map((m) => `  ${JSON.stringify(m.name)}: ${ident(m.name)},`).join("\n")}\n}`,
  )
  const cfg = disco.configPath ? `(_config as { default?: any }).default ?? _config` : "{}"
  lines.push(`const config: any = ${cfg}`)
  lines.push("")
  lines.push(
    `export const RabbatPartition = definePartition({ schema: compileSchema(schema as any), modules: modules as any, auth: config.auth })`,
  )
  lines.push(`export default defineWorker({ partitionFor: config.partitionFor })`)
  lines.push("")
  return lines.join("\n")
}

/**
 * The generated wrangler config (emitted beside the worker). `main` is relative
 * to that file, so it points at the generated `worker.ts` in the same directory.
 */
export function generateWrangler(name: string, compatDate: string): string {
  const config = {
    name,
    main: "worker.ts",
    compatibility_date: compatDate,
    compatibility_flags: ["nodejs_compat"],
    durable_objects: { bindings: [{ name: "RABBAT_PARTITION", class_name: "RabbatPartition" }] },
    migrations: [{ tag: "v1", new_sqlite_classes: ["RabbatPartition"] }],
    r2_buckets: [{ binding: "RABBAT_BUCKET", bucket_name: name }],
    assets: { not_found_handling: "single-page-application" },
    observability: { enabled: true },
  }
  return JSON.stringify(config, null, 2)
}

/** The generated, fully-typed `api` tree the React app imports. */
export function generateApi(disco: Discovery): string {
  const from = disco.generatedDir
  const lines: string[] = []
  lines.push("// Generated by @rabbat/vite. Do not edit.")
  lines.push(`import type { RefOf } from "@rabbat/functions"`)
  const used = disco.apiModules.filter((m) => scanExports(m.path).length > 0)
  for (const m of used) {
    lines.push(`import type * as ${ident(m.name)} from ${JSON.stringify(importSpec(from, m.path))}`)
  }
  lines.push("")
  lines.push("export const api = {")
  for (const m of used) {
    lines.push(`  ${JSON.stringify(m.name)}: {`)
    for (const fn of scanExports(m.path)) {
      lines.push(
        `    ${JSON.stringify(fn)}: { name: ${JSON.stringify(`${m.name}:${fn}`)} } as unknown as RefOf<typeof ${ident(m.name)}.${fn}>,`,
      )
    }
    lines.push("  },")
  }
  lines.push("} as const")
  lines.push("")
  lines.push("export const internal = {} as const")
  lines.push("")
  return lines.join("\n")
}
