import { relative } from "node:path"
import { type Discovery, scanFunctionExports } from "./discover.js"

/** A relative, POSIX, extensionless import specifier from `fromDir` to `target`. */
function importSpec(fromDir: string, target: string): string {
  let rel = relative(fromDir, target).replace(/\\/g, "/").replace(/\.ts$/, "")
  if (!rel.startsWith(".")) rel = "./" + rel
  return rel
}

function ident(name: string): string {
  return "_" + name.replace(/[^A-Za-z0-9_$]/g, "_")
}

/**
 * The generated Worker entry (emitted to `<backendRoot>/_generated/worker.ts`).
 * It imports the schema and every function module, assembles the `modules` map,
 * and exports the `RabbatPartition` Durable Object and the default Worker handler
 * — so the user never writes this wiring.
 */
export function generateWorkerEntry(disco: Discovery): string {
  const from = disco.generatedDir
  const lines: string[] = []
  lines.push("// Generated by @rabbat/vite. Do not edit.")
  lines.push(`import { compileSchema } from "@rabbat/schema"`)
  lines.push(`import { definePartition, defineWorker } from "@rabbat/server"`)
  lines.push(`import { schema } from ${JSON.stringify(importSpec(from, disco.schemaPath))}`)
  for (const m of disco.modules) {
    lines.push(`import * as ${ident(m.name)} from ${JSON.stringify(importSpec(from, m.path))}`)
  }
  disco.serverRoutes.forEach((r, i) => {
    lines.push(`import _api${i} from ${JSON.stringify(importSpec(from, r.path))}`)
  })
  if (disco.configPath) {
    lines.push(`import * as _config from ${JSON.stringify(importSpec(from, disco.configPath))}`)
  }
  lines.push("")
  lines.push(
    `const modules = {\n${disco.modules.map((m) => `  ${JSON.stringify(m.name)}: ${ident(m.name)},`).join("\n")}\n}`,
  )
  const apiList = disco.serverRoutes.map((_, i) => `_api${i}`).join(", ")
  lines.push(`const apiRoutes = [${apiList}]`)
  const cfg = disco.configPath ? `(_config as { default?: any }).default ?? _config` : "{}"
  lines.push(`const config: any = ${cfg}`)
  lines.push("")
  lines.push(
    `export const RabbatPartition = definePartition({ schema: compileSchema(schema as any, { strictIndexes: config.strictIndexes }), modules: modules as any, auth: config.auth, flushBytes: config.flushBytes, maxMessageBytes: config.maxMessageBytes, serviceKey: config.serviceKey })`,
  )
  lines.push(
    `export default defineWorker({ partitionFor: config.partitionFor, authenticate: config.authenticate, apiRoutes, auth: config.auth, dbAdmin: config.dbAdmin })`,
  )
  lines.push("")
  return lines.join("\n")
}

/**
 * The generated wrangler config (emitted beside the worker). `main` is relative
 * to that file, so it points at the generated `worker.ts` in the same directory.
 */
export function generateWrangler(name: string, compatDate: string): string {
  const config = {
    name,
    main: "worker.ts",
    compatibility_date: compatDate,
    compatibility_flags: ["nodejs_compat"],
    durable_objects: { bindings: [{ name: "RABBAT_PARTITION", class_name: "RabbatPartition" }] },
    migrations: [{ tag: "v1", new_sqlite_classes: ["RabbatPartition"] }],
    r2_buckets: [{ binding: "RABBAT_BUCKET", bucket_name: name }],
    assets: {
      not_found_handling: "single-page-application",
      // Run the Worker first for sync + function + API + admin paths; everything
      // else is served as the SPA.
      run_worker_first: ["/ws", "/functions", "/api/*", "/_rabbat/*"],
    },
    observability: { enabled: true },
  }
  return JSON.stringify(config, null, 2)
}

/** The generated, fully-typed `api` + `internal` trees the app imports. */
export function generateApi(disco: Discovery): string {
  const from = disco.generatedDir
  const lines: string[] = []
  lines.push("// Generated by @rabbat/vite. Do not edit.")
  lines.push(`import type { RefOf } from "@rabbat/functions"`)
  // Every module that exports at least one function (public or internal).
  const scanned = disco.apiModules.map((m) => ({ m, fns: scanFunctionExports(m.path) }))
  const used = scanned.filter(({ fns }) => fns.length > 0)
  for (const { m } of used) {
    lines.push(`import type * as ${ident(m.name)} from ${JSON.stringify(importSpec(from, m.path))}`)
  }
  lines.push("")

  const tree = (which: "public" | "internal"): string[] => {
    const out: string[] = []
    for (const { m, fns } of used) {
      const entries = fns.filter((f) => (which === "internal" ? f.internal : !f.internal))
      if (entries.length === 0) continue
      out.push(`  ${JSON.stringify(m.name)}: {`)
      for (const f of entries) {
        out.push(
          `    ${JSON.stringify(f.name)}: { name: ${JSON.stringify(`${m.name}:${f.name}`)} } as unknown as RefOf<typeof ${ident(m.name)}.${f.name}>,`,
        )
      }
      out.push("  },")
    }
    return out
  }

  lines.push("export const api = {")
  lines.push(...tree("public"))
  lines.push("} as const")
  lines.push("")
  const internalEntries = tree("internal")
  lines.push("export const internal = {")
  lines.push(...internalEntries)
  lines.push("} as const")
  lines.push("")
  return lines.join("\n")
}
