import { relative } from "node:path"
import type { RouteDiscovery } from "./routes.js"

/** A relative, POSIX, extensionless import specifier from `fromDir` to `target`. */
export function routeSpec(fromDir: string, target: string): string {
  let rel = relative(fromDir, target).replace(/\\/g, "/").replace(/\.tsx?$/, "")
  if (!rel.startsWith(".")) rel = "./" + rel
  return rel
}

/** Type literal for a pattern's params: `/posts/:id` → `{ id: string }`. */
export function paramsType(pattern: string): string {
  const names = pattern
    .split("/")
    .filter((s) => s.startsWith(":") || s.startsWith("*"))
    .map((s) => s.slice(1))
  if (names.length === 0) return "Record<string, never>"
  return "{ " + names.map((n) => `${n}: string`).join("; ") + " }"
}

/**
 * The route manifest (lazy imports for code-splitting) the runtime router
 * consumes. Framework-agnostic: it lazy-imports whatever page/layout files were
 * discovered, so the same generator serves React, Vue, or Svelte.
 */
export function generateManifest(disco: RouteDiscovery, outDir: string): string {
  const L = (path: string) => JSON.stringify(routeSpec(outDir, path))
  const layouts = disco.layouts
    .map((l) => `  { id: ${JSON.stringify(l.id)}, load: () => import(${L(l.file)}) },`)
    .join("\n")
  const routes = disco.routes
    .map(
      (r) =>
        `  {\n    pattern: ${JSON.stringify(r.pattern)}, ssr: ${r.ssr}, layouts: ${JSON.stringify(r.layouts)},\n` +
        `    load: () => import(${L(r.pageFile)}),\n    loadRoute: () => import(${L(r.routeFile)}),\n  },`,
    )
    .join("\n")
  return [
    "// Generated by @rabbat/vite. Do not edit.",
    `import type { RouterManifest } from "@rabbat/router"`,
    "",
    "export const manifest: RouterManifest = {",
    "  layouts: [",
    layouts,
    "  ],",
    "  routes: [",
    routes,
    "  ],",
    "}",
    "",
  ].join("\n")
}

/** The agnostic `Routes` type map (pattern → params). Framework adapters build a
 *  typed `Link`/`navigate` on top of this. */
export function generateRoutesInterface(disco: RouteDiscovery): string {
  const entries = disco.routes
    .map((r) => `  ${JSON.stringify(r.pattern)}: { params: ${paramsType(r.pattern)} }`)
    .join("\n")
  return ["export interface Routes {", entries, "}", "", "export type RoutePath = keyof Routes", ""].join("\n")
}
