import type { AnyRegistered } from "@rabbat/functions"

/** Options controlling how generated module imports are spelled. */
export interface GenerateApiOptions {
  /** Prefix prepended to each module name to form its import specifier. Defaults to `"../"`. */
  importPrefix?: string
  /** Extension appended to each module import specifier. Defaults to `".js"`. */
  importExtension?: string
}

/**
 * Generate the text of an `api.ts` file from a map of modules to their exported
 * registered functions.
 *
 * The generated file imports each module with `import type * as _<module>` so
 * the handler code is fully erased — only the static type survives, which is
 * what `RefOf<typeof ...>` consumes. At runtime the `api`/`internal` trees are
 * plain `{ name }` objects cast to the appropriate `RefOf<>`.
 *
 * Functions with `internal === true` are placed under `internal` and excluded
 * from `api`; functions with `internal === false` go under `api`. A module with
 * no exported functions is skipped entirely.
 */
export function generateApi(
  modules: Record<string, Record<string, AnyRegistered>>,
  options?: GenerateApiOptions,
): string {
  const importPrefix = options?.importPrefix ?? "../"
  const importExtension = options?.importExtension ?? ".js"

  const moduleNames = Object.keys(modules).filter(
    (name) => Object.keys(modules[name]!).length > 0,
  )

  const importLines = moduleNames.map(
    (name) => `import type * as _${name} from "${importPrefix}${name}${importExtension}"`,
  )

  const apiTree: string[] = []
  const internalTree: string[] = []

  for (const moduleName of moduleNames) {
    const fns = modules[moduleName]!
    const apiEntries: string[] = []
    const internalEntries: string[] = []
    for (const exportName of Object.keys(fns)) {
      const fn = fns[exportName]!
      const entry = `${exportName}: { name: "${moduleName}:${exportName}" } as unknown as RefOf<typeof _${moduleName}.${exportName}>`
      if (fn.internal) {
        internalEntries.push(entry)
      } else {
        apiEntries.push(entry)
      }
    }
    if (apiEntries.length > 0) {
      apiTree.push(`  ${moduleName}: {\n${apiEntries.map((e) => `    ${e},`).join("\n")}\n  },`)
    }
    if (internalEntries.length > 0) {
      internalTree.push(`  ${moduleName}: {\n${internalEntries.map((e) => `    ${e},`).join("\n")}\n  },`)
    }
  }

  const lines: string[] = []
  lines.push("// Auto-generated by @rabbat/codegen. Do not edit.")
  lines.push('import type { RefOf } from "@rabbat/functions"')
  for (const importLine of importLines) lines.push(importLine)
  lines.push("")
  lines.push(apiTree.length > 0 ? `export const api = {\n${apiTree.join("\n")}\n} as const` : "export const api = {} as const")
  lines.push("")
  lines.push(
    internalTree.length > 0
      ? `export const internal = {\n${internalTree.join("\n")}\n} as const`
      : "export const internal = {} as const",
  )
  lines.push("")

  return lines.join("\n")
}
