import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { join, relative } from "node:path"
import {
  discoverRoutes,
  generateManifest,
  generateRoutesInterface,
  generatedDir,
  routeSpec,
  type RouteDiscovery,
} from "@rabbat/vite/codegen"

/** The typed React `<Link>` / `useNavigate` over the agnostic `Routes` map. */
export function generateReactRouteTypes(disco: RouteDiscovery): string {
  return [
    "// Generated by @rabbat/vite-react. Do not edit.",
    `import { Link as BaseLink, useRouter } from "@rabbat/react"`,
    `import { buildHref } from "@rabbat/router"`,
    `import type { ReactElement } from "react"`,
    `import type { LinkProps as BaseLinkProps } from "@rabbat/react"`,
    "",
    generateRoutesInterface(disco),
    "type ParamsFor<P extends RoutePath> = Routes[P][\"params\"]",
    "type TypedLinkProps<P extends RoutePath> = Omit<BaseLinkProps, \"to\" | \"params\"> & { to: P } &",
    "  (keyof ParamsFor<P> extends never ? { params?: undefined } : { params: ParamsFor<P> })",
    "",
    "/** Type-safe <Link>: `to` autocompletes route patterns; params are required when the path has them. */",
    "export const Link = BaseLink as unknown as <P extends RoutePath>(props: TypedLinkProps<P>) => ReactElement | null",
    "",
    "/** Type-safe imperative navigation. */",
    "export function useNavigate() {",
    "  const router = useRouter()",
    "  return <P extends RoutePath>(",
    "    to: P,",
    "    opts?: { params?: ParamsFor<P>; search?: Record<string, unknown>; replace?: boolean },",
    "  ) => router.navigate(buildHref(to, opts?.params as Record<string, string>), opts)",
    "}",
    "",
  ].join("\n")
}

/** The React client entry that replaces a hand-written `main.tsx`. */
export function generateReactEntry(outDir: string, manifestPath: string): string {
  return [
    "// Generated by @rabbat/vite-react. Do not edit.",
    `import { mountRabbatApp } from "@rabbat/react"`,
    `import { manifest } from ${JSON.stringify(routeSpec(outDir, manifestPath))}`,
    "",
    "mountRabbatApp({ manifest })",
    "",
  ].join("\n")
}

function writeIfChanged(path: string, content: string): void {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return
  writeFileSync(path, content)
}

/**
 * Discover `routes/` (React `.page.tsx` convention) and write the manifest, the
 * typed React `Link`/`useNavigate`, and the client entry into
 * `<routesDir>/_generated/`. Returns the entry URL for index.html injection.
 */
export function writeReactRouteCodegen(root: string): { entryUrl: string } | null {
  const disco = discoverRoutes(root, { pageExt: ".page.tsx" })
  if (!disco) return null
  const outDir = generatedDir(root) // all generated code lives in rabbat/_generated/
  mkdirSync(outDir, { recursive: true })
  const manifestPath = join(outDir, "manifest.ts")
  writeIfChanged(manifestPath, generateManifest(disco, outDir))
  writeIfChanged(join(outDir, "routes.tsx"), generateReactRouteTypes(disco))
  writeIfChanged(join(outDir, "entry.tsx"), generateReactEntry(outDir, manifestPath))
  return { entryUrl: "/" + relative(root, join(outDir, "entry.tsx")).replace(/\\/g, "/") }
}
